---
- hosts: all
  become: yes
  roles:
    - role: geerlingguy.java
  
  tasks:
    - name: get the package tomcat
      get_url:
         url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.57/bin/apache-tomcat-8.5.57.tar.gz
         dest: /usr/local
    - name: extract the file
      unarchive:
        src: /usr/local/apache-tomcat-8.5.57.tar.gz
        dest: /usr/local/
        remote_src: yes

    - name: check the file exit or not
      stat:
        path: /usr/local/praveen.txt
      register: st

    - name: start the tomcat service
      shell: nohup /usr/local/apache-tomcat-8.5.57/bin/startup.sh
      notify:
        - create a flag
      when: st.stat.exists == False

  handlers:
    - name: create a flag
      file:
        path: /usr/local/praveen.txt
        state: touch


